---
  - name: PLAY 1 - ISSUE SNMP COMMANDS
    hosts: iosxe
    connection: local
    gather_facts: no
    
    tasks:

      - name: TASK1 - DEPLOY SNMP COMMANDS
        ios_command:
          commands:
            - show run | inc snmp
          provider:
            username: "{{ username }}"
            password: "{{ password }}"
            host: "{{ inventory_hostname }}"
            timeout: 60

      - name: TASK 2- DEPLOY SNMP COMMANDS
        ios_config:
          commands:
            - snmp-server community public RO
          provider:
            username: "{{ username }}"
            password: "{{ password }}"
            host: "{{ inventory_hostname }}"
            timeout: 60