---
- name: build the network
  hosts: routers
  connection: network_cli
  tasks:
    - name: configure Hostname and Domain Name
      ios_system:
        hostname: "{{ inventory_hostname }}"
        domain_name: "{{ domain_name }}"
        lookup_enabled: no

    - name: configure ip address on wan links
      tags: t2
      ios_l3_interfaces:
        config:
          - name: "{{ item.name }}"
            ipv4:
              - address: "{{ item.ipv4 }}"
        state: merged
      loop: "{{ router_interfaces[inventory_hostname] }}"
      when: "'Loopback0' not in item.name"

    - name: configure ip address on loopback
      tags: t3
      ios_l3_interface:
        name: "{{ item.name }}"
        ipv4: "{{ item.ipv4 }}"
      loop: "{{ router_interfaces[inventory_hostname] }}"
      when: "'Loopback0' in item.name"

    - name: configure ospf
      tags: t4
      ios_config:
        parents: router ospf {{ ospf_process }}
        lines:
          - router-id {{ loopback_prefix | ipv4(ansible_host_id) | ipaddr('address')}}

    - name: configure ospf on interfaces
      tags: t5
      ios_config:
        parents: interface {{ item.name }}
        lines:
          - ip ospf {{ ospf_process }} area {{ ospf_area }}
          - ip ospf network point-to-point
      loop: "{{ router_interfaces[inventory_hostname] | selectattr('ospf') | list }}"

    - name: configure ospf passive interfaces
      tags: t6
      ios_config:
        parents: router ospf {{ ospf_process }}
        lines: passive-interface {{item.name}}
      loop: "{{ router_interfaces[inventory_hostname] | selectattr('ospf','equalto','passive') | list }}"

    - name: save running to startup when modified
      ios_config:
        save_when: modified
