---
- name: build the network
  hosts: cisco

  tasks:

  - name: configure Hostname and Domain Name
    ios_system:
      hostname: "{{ hostname }}"
      domain_name: "{{ domain }}"
      lookup_enabled: no
  
  - name: configure OSPF
    ios_config:
      lines: 
        - router ospf 1
        - network 0.0.0.0 255.255.255.255 area 0

  - name: save running to startup when modified
    ios_config:
      save_when: modified