---
- name: generate initial config from Jinja2
  hosts: localhost
  gather_facts: no
  tasks:
    - name: create configs directory
      file: path=configs  state=directory

- name: Generate initial config from Jinja2
  hosts: routers
  gather_facts: no
  tasks:
    - name: generate cisco basic config
      template:
        src: "templates/initial_config.j2"
        dest: "configs/{{inventory_hostname}}.cfg"
      delegate_to: localhost
