---
- name: first play
  hosts: routers
  connection: network_cli

  tasks:
    - name: first task
      ios_command:
        commands: show ip int br
      register: var_br
    - name: second task
      debug:
        var: var_br
