core_vlans:
  - name: l3_core_vlan
    vlan_id: 200
    interface: GigabitEthernet0/3

svi_interfaces:
  - name: Vlan10
    ipv4: 10.1.10.0/24
    vrrp: yes
    ospf: passive
  - name: Vlan20
    ipv4: 10.1.20.0/24
    vrrp: yes
    ospf: passive
  - name: Vlan100
    ipv4: 10.1.100.0/24
    vrrp: yes
    ospf: passive
