---
- name: validate network reachability
  hosts: core,wan
  vars:
    host_id: 10
    packet_count: 10
  tasks:
    - name: get all svi prefixes
      tags: t1
      set_fact:
        all_svi_prefixes: "{{ svi_interfaces | selectattr('vrrp') |
          map(attribute='ipv4') | list }}"
      run_once: yes
      delegate_to: localhost

    - name: ping hosts in all vlans
      tags: t2
      ios_ping:
        dest: "{{ item | ipaddr(10) | ipaddr('address') }}"
      loop: "{{ all_svi_prefixes }}"

    - name: include all loobacks
      tags: t3
      include_vars: facts.yml
      run_once: yes
      delegate_to: localhost

    - name: ping loopbacks for all core and wan devices
      tags: t4
      ios_ping:
        dest: "{{ item }}"
        count: "{{ packet_count }}"
      loop: "{{ all_loopbacks }}"
