---
- name: first play
  hosts: all
  connection: network_cli

  tasks:
    - name: first task
      ios_command:
        commands: show ip int br
      register: int_br
    - name: second task
      debug:
        var: int_br
