---
- name: configure all lan switches
  hosts: lan
  tags: lan
  connection: network_cli
  tasks:
    - name: task1-configure hostname and domain name
      tags: t1
      ios_system:
        hostname: "{{ inventory_hostname }}"
        domain_name: "{{ domain_name }}"
        lookup_enabled: no
        name_servers: "{{ name_servers }}"

    - name: task2-configure ntp
      tags: t2
      ios_ntp:
        server: "{{ ntp_server }}"
        logging: true
        state: present

    - name: task3-configure interfaces
      tags: t3
      ios_interface:
        name: "{{ item.name }}"
        description: "{{ item.description }}"
        duplex: "{{ intf_duplex }}"
        mtu: "{{ intf_mtu }}"
        state: up
      loop: "{{ interfaces[inventory_hostname] }}"
      register: ios_intf

    - name: task4-create l2 vlans
      tags: t4
      ios_vlan:
        vlan_id: "{{ item.vlan_id }}"
        name: "{{ item.name  }}"
      loop: "{{ vlans }}"

    - name: task5-configure l2 trunks
      tags: t5
      ios_l2_interface:
        name: "{{ item.name }}"
        mode: "{{ item.mode }}"
        trunk_allowed_vlans: "{{ vlans | map(attribute='vlan_id') | join(',') }}"
        state: present
      loop: "{{ interfaces[inventory_hostname] | selectattr('mode','equalto','trunk') | list }}"

    - name: task6-enable dot1q trunks
      tags: t6
      ios_config:
        lines:
          - switchport trunk encapsulation dot1q
        parents: interface {{item.name}}
      loop: "{{ interfaces[inventory_hostname] | selectattr('mode','equalto','trunk') | list }}"

    - name: task7-configure access ports
      tags: t7
      ios_l2_interface:
        name: "{{ item.name }}"
        mode: "{{ item.mode}}"
        access_vlan: "{{ item.vlan }}"
        state: present
      loop: "{{ interfaces[inventory_hostname] | selectattr('mode','equalto','access') | list }}"

- name: configure all core l3 switches
  hosts: core
  tags: l3_core
  tasks:
    - name: task8-create l3 vlan interfaces
      tags: t8
      ios_l3_interface:
        name: "{{item.name }}"
        ipv4: "{{item.ipv4 | ipv4(hst_svi_id)}}"
      loop: "{{svi_interfaces}}"

    - name: task9-enable the vlan interfaces
      tags: t9
      ios_interface:
        name: "{{ item.name }}"
        enabled: true
      loop: "{{ svi_interfaces }}"

    - name: task10-create vrrp configs
      tags: t10
      ios_config:
        parents: interface {{ item.name }}
        lines:
          - vrrp {{item.name.split('Vlan')[1]}} priority {{ hst_vrrp_priority }}
          - vrrp {{item.name.split('Vlan')[1]}} ip {{item.ipv4 | ipv4(254)|ipaddr('address')}}
      loop: "{{svi_interfaces | selectattr('vrrp','equalto',true) | list }}"
